---
instance_groups:
  - name:      minio
    instances: 1
    azs:       (( grab params.availability_zones || meta.default.azs ))
    stemcell:  default
    networks:
      - name: (( grab params.network || "minio"))
    vm_type:   (( grab params.vm_type || "default" ))
    persistent_disk_type: (( grab params.disk_type || "minio" )) 
    jobs:
    - name: minio-server
      release: minio
      templates:
      - name: minio-server
      properties:
        server_cert: (( vault meta.vault "/ssl/server:certificate" ))
        server_key: (( vault meta.vault "/ssl/server:key" ))
        ca_cert: (( vault meta.vault "/ssl/ca:certificate"))
        dns_alias: (( grab meta.default.domain_base ))
        credential: 
          accesskey: (( vault meta.vault "/access_token:accesskey" ))
          secretkey: (( vault meta.vault "/access_token:secretkey" ))
        port: (( grab params.port || 9000 ))
    properties:
      debug: false 

update:
  serial:            false
  canaries:          1
  max_in_flight:     1
  max_errors:        1
  canary_watch_time: 5000-600000
  update_watch_time: 5000-600000

stemcells:
  - alias:   default
    os:      (( grab params.stemcell_os      || "ubuntu-trusty" ))
    version: (( grab params.stemcell_version || "latest" ))

releases:
  - name: "minio"
    version: "2018-06-08T03-49-38Z"
    url: "https://bosh.io/d/github.com/minio/minio-boshrelease?v=2018-06-08T03-49-38Z"
    sha1: "3a5ae84f8b2be9ee640d545c489633e36c0674dd"

meta:
  default:
    azs: [z1]
    domain_base: (( concat "minio." params.network "." params.env "-minio.bosh" ))

exodus:
  url: (( concat "https://" params.external_domain ":" instance_groups.minio.jobs.minio-server.properties.port ))
